name: CI/CD

on:
  push:
    branches: master
    tags: v*
  pull_request:
    branches: master

env:
  GO_VERSION: '^1.16'

jobs:

  test:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v3.0.1
        with:
          path: |
            ~/go/bin
            ~/go/pkg
            ~/go/src
            ~/.cache/go-build
            ~/.cache/golangci-lint
            .gobincache
          key: v3-test-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            v3-test-${{ runner.os }}-

      - run: echo "PATH=$PWD/.gobincache:$PATH" >> $GITHUB_ENV
      - run: go generate
      - run: golangci-lint run
      - run: go test
